elements:
  - name: hydrogen
    symbol: H
    atomic_number: 1
    atomic_weight: 1.008
    protons: 1
    electrons: 1
    density: 0.08988
    electronegativity: 2.20
    atomic_radius: 53
  - name: helium
    symbol: He
    atomic_number: 2
    atomic_weight: 4.002602
    protons: 2
    electrons: 2
    density: 0.1786
    electronegativity: 0.00
    atomic_radius: 31
  - name: lithium
    symbol: Li
    atomic_number: 3
    atomic_weight: 6.94
    protons: 3
    electrons: 3
    density: 0.534
    electronegativity: 0.98
    atomic_radius: 167
  - name: beryllium
    symbol: Be
    atomic_number: 4
    atomic_weight: 9.0122
    protons: 4
    electrons: 4
    density: 1.848
    electronegativity: 1.57
    atomic_radius: 112
  - name: boron
    symbol: B
    atomic_number: 5
    atomic_weight: 10.81
    protons: 5
    electrons: 5
    density: 2.34
    electronegativity: 2.04
    atomic_radius: 87
  - name: carbon
    symbol: C
    atomic_number: 6
    atomic_weight: 12.011
    protons: 6
    electrons: 6
    density: 2.267
    electronegativity: 2.55
    atomic_radius: 70
  - name: nitrogen
    symbol: N
    atomic_number: 7
    atomic_weight: 14.007
    protons: 7
    electrons: 7
    density: 0.001251
    electronegativity: 3.04
    atomic_radius: 65
  - name: oxygen
    symbol: O
    atomic_number: 8
    atomic_weight: 15.999
    protons: 8
    electrons: 8
    density: 0.001429
    electronegativity: 3.44
    atomic_radius: 60